apiVersion: v1
kind: Pod
metadata:
  name: infinispan-node0
  labels:
    app: hotrod-rs-cluster-test
spec:
  containers:
    - name: infinispan
      image: infinispan/server:15.1
      args:
        - "-n"
        - "node0"
        - "-g"
        - "hotrod-rs-cluster-test"
        - "-j"
        - "kubernetes"
        - "-Djgroups.dns.query=hotrod-rs-cluster-test.default.svc.cluster.local"
        - "-Dinfinispan.external.host=127.0.0.1"
        - "-Dinfinispan.external.port=11222"
      env:
        - name: USER
          value: testuser
        - name: PASS
          value: unused-but-required
      ports:
        - containerPort: 11222
          hostPort: 11222
      volumeMounts:
        - name: config
          mountPath: /opt/infinispan/server/conf/infinispan.xml
          subPath: infinispan.xml
        - name: config
          mountPath: /opt/infinispan/server/conf/users.properties
          subPath: users.properties
        - name: config
          mountPath: /opt/infinispan/server/conf/groups.properties
          subPath: groups.properties
  volumes:
    - name: config
      configMap:
        name: infinispan-config
